steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'docker'
    args: ['build', '-t',
           'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/awsbe:${SHORT_SHA}', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'docker'
    args: ['push',  'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/awsbe:${SHORT_SHA}']

  # Docker push to Google Artifact Registry
  # - name: 'gcr.io/cloud-builders/kubectl'
  #   # entrypoint: 'kubectl'
  #   # args: ['set', 'image', 'deployment/awsbe2', 'awsbe2=us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/awsbe:${SHORT_SHA}']
  #   args: ['apply', '-f', 'deploy.yaml']
  #   env:
  #     - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  #     - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'kubectl'
    args: ['apply', '-f', 'deploy.yaml']

options:
 logging: CLOUD_LOGGING_ONLY