steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'docker'
    args: ['build', '-t',
           'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_ARTIFACT_REGISTRY_REPO}:${SHORT_SHA}', '.']

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'docker'
    args: ['push',  'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/${_ARTIFACT_REGISTRY_REPO}:${SHORT_SHA}']

  # custom build steps https://cloud.google.com/build/docs/configuring-builds/use-community-and-custom-builders
  # prepare deploy.yaml file
  - name: 'gcr.io/${PROJECT_ID}/envsubst'
    args: ["deploy.yaml"]
    env:
      - 'PROJECT_ID=${PROJECT_ID}'
      - '_ARTIFACT_REGISTRY_REPO=${_ARTIFACT_REGISTRY_REPO}'
      - 'SHORT_SHA=${SHORT_SHA}'


  # python test
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'python'
    args: ['pp.py']

  # get k8s config
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['container', 'clusters', 'get-credentials', '${_CLOUDSDK_CONTAINER_CLUSTER}', '--zone', '${_CLOUDSDK_COMPUTE_ZONE}', '--project', '${PROJECT_ID}']

  # run deployment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'kubectl'
    args: ['apply', '-f', 'deploy.yaml']

substitutions:
    _ARTIFACT_REGISTRY_REPO: 'awsbe'
    _CLOUDSDK_CONTAINER_CLUSTER: cluster-1
    # CLOUDSDK_COMPUTE_REGION: 
    _CLOUDSDK_COMPUTE_ZONE: us-central1-c

options:
 logging: CLOUD_LOGGING_ONLY