apiVersion: batch/v1
kind: CronJob
metadata:
  name: awsbecron
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: awsbecron
            image: us-central1-docker.pkg.dev/zippy-parity-381314/awsbe/awsbe:v4
            command: ["bash"]
            args: ["-c", "python /code/manage.py testcommand"]
          nodeSelector:
            cloud.google.com/gke-nodepool: highcpu
          restartPolicy: OnFailure
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: awsbecron-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: CronJob
    name: awsbecron
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
