apiVersion: batch/v1beta1
kind: CronJob
meta:
  name: awsbe-cron
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
           - name: awsbe-cron
             image: us-central1-docker.pkg.dev/zippy-parity-381314/awsbe/awsbe:v4
             command: ["bash"]
             args: ["-c", "python /source/manage.py testcommand"]
          restartPolicy: OnFailure