apiVersion: batch/v1
kind: CronJob
metadata:
  name: testcron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: testcron
            image: us-central1-docker.pkg.dev/zippy-parity-381314/awsbe/awsbe
            command: ["bash"]
            args: ["-c", "python /code/manage.py testcron"]
          nodeSelector:
            cloud.google.com/gke-nodepool: highcpu
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: testcommand
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: testcommand
            image: us-central1-docker.pkg.dev/zippy-parity-381314/awsbe/awsbe
            command: ["bash"]
            args: ["-c", "python /code/manage.py testcommand"]
          nodeSelector:
            cloud.google.com/gke-nodepool: highcpu
          restartPolicy: OnFailure
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: testcommand-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: CronJob
    name: testcommand
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
