apiVersion: batch/v1
kind: CronJob
metadata:
  name: awsbecron
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: awsbecron
             image: us-central1-docker.pkg.dev/zippy-parity-381314/awsbe/awsbe:v4
             command: ["bash"]
             args: ["-c", "python /code/manage.py testcommand"]
          nodeSelector:
            cloud.google.com/gke-nodepool: highcpu
          restartPolicy: OnFailure