apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo1
  labels:
    app: mongo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo1
  template:
    metadata:
      labels:
        app: mongo1
    spec:
      containers:
      - name: mongo1
        image: mongo:5.0
        ports:
          - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "example"
      nodeSelector:
        cloud.google.com/gke-nodepool: mongo-m1
---
apiVersion: v1
kind: Service
metadata:
  name: mongo1-nhlcd
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo1
  sessionAffinity: None
  type: ClusterIP